name: Sports Betting AI - Continuous Execution

on:
  schedule:
    # Run every 30 minutes, 24/7, 365 days/year
    - cron: '*/30 * * * *'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  run_betting_ai:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Run Advanced Learning AI
        run: python advanced_learning.py
        timeout-minutes: 5
      
      - name: Check if predictions exist
        run: |
          if [ -f "performance_report.json" ]; then
            echo "SUCCESS: AI execution completed"
            cat performance_report.json
          fi
